name 'setup_nexus'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures setup_nexus'
long_description 'Installs/Configures setup_nexus'
version '0.1.0'
