---
driver:
  name: docker
  binary: /usr/bin/docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[setup_hello_world::default]
    attributes:
